[dark-theme]
gtk-theme = "Yaru-Blue-dark"
gtk-icon = "Papirus-Dark"
gtk-cursor = "Bibata-Modern-Ice"
cursor-size = 24
background = "/home/mewer/.local/share/walls/b-781.jpg"
sunset-temperature = "4700"

[light-theme]
gtk-theme = "Yaru-Blue-light"
gtk-icon = "Papirus-Dark"
gtk-cursor = "Bibata-Modern-Classic"
cursor-size = 22
background = "/home/mewer/.local/share/walls/b-005.jpg"
sunset-temperature = "6000"

[current]
mode = "Dark"
